### ISSUE TITLE
Unable to run example following readme

### ISSUE THREAD

**Issue by rhoudroge** [strictdoc-project/strictdoc-examples#3]
Hi, running the instructions from the README.md results in the following error using python 3.10

```textx.exceptions.TextXSyntaxError: /tcenas/home/ramih/repos/strictdoc-examples/examples/example_08.sdoc:6:6: Expected ' ' => '-001 REFS:* - TYPE: F'```

**Comment by stanislaw** [comment]
Hi @rhoudroge , 

Thanks for reporting this. There have been two SDoc markup-related migrations going on, and one example in this repo became outdated.

Could you try to change `REFS` -> `RELATIONS` and move them to be defined last for each requirement, i.e., change this:

```
[REQUIREMENT]
UID: REQ-002
REFS:
- TYPE: File
  VALUE: examples/example_source_files/file.py
TITLE: Source range reference
STATEMENT: This requirement references a range in the file.
```

to this


```
[REQUIREMENT]
UID: REQ-002
TITLE: Source range reference
STATEMENT: This requirement references a range in the file.
RELATIONS:
- TYPE: File
  VALUE: examples/example_source_files/file.py
```

I will update the example later today but for now you could try to change it manually.

**Comment by rhoudroge** [comment]
That works, thanks!

**Comment by stanislaw** [comment]
Closed by https://github.com/strictdoc-project/strictdoc-examples/pull/5.
